%if "#{==:#{@navin_pane_split},yes}"
  bind-key "|" split-window -h -c "#{pane_current_path}"
  bind-key "-" split-window -v -c "#{pane_current_path}"
  bind-key "_" split-window -fv -c "#{pane_current_path}"
  bind-key "\\" split-window -fh -c "#{pane_current_path}"
%endif

%if "#{==:#{@navin_win_index_mgmt},yes}"
  bind-key -r "<" swap-window -d -t -1
  bind-key -r ">" swap-window -d -t +1
%endif