set -ogq @navin_pane_resize "5"
set -ogq @navin_nav "yes"
set -ogq @navin_renumber_windows "on"
set -ogq @navin_arrow_nav "yes"
set -ogq @navin_repeat_time "1000"
set -ogq @navin_vim_pane_resizing "yes"
set -ogq @navin_layout_mgmt "yes"
set -ogq @navin_tab_nav "yes"