%if "#{==:#{@navin_pane_split},yes}"
  bind-key "|" split-window -h -c "#{pane_current_path}"
  bind-key "-" split-window -v -c "#{pane_current_path}"
  bind-key "_" split-window -fv -c "#{pane_current_path}"
  bind-key "\\" split-window -fh -c "#{pane_current_path}"
%endif

%if "#{==:#{@navin_win_index_mgmt},yes}"
  bind-key -r "<" swap-window -d -t -1
  bind-key -r ">" swap-window -d -t +1
%endif

%if "#{==:#{@navin_vim_pane_resizing},yes}"
  bind-key -r H resize-pane -L "#{@navin_pane_resize}"
  bind-key -r J resize-pane -D "#{@navin_pane_resize}"
  bind-key -r K resize-pane -U "#{@navin_pane_resize}"
  bind-key -r L resize-pane -R "#{@navin_pane_resize}"
%endif