%if "#{==:#{@tpc_vim_mode_nav},yes}"
  bind h select-pane -L
  bind C-h select-pane -L
  bind j select-pane -D
  bind C-j select-pane -D
  bind k select-pane -U
  bind C-k select-pane -U
  bind l select-pane -R
  bind C-l select-pane -R
%endif

%if "#{==:#{@tpc_nav},yes}"
  bind -n M-Left select-pane -L
  bind -n M-Right select-pane -R
  bind -n M-Up select-pane -U
  bind -n M-Down select-pane -D
%endif

%if "#{==:#{@tpc_renumber_windows},on}"
  set-option -gq renumber-windows on
%endif
