%if "#{==:#{@navin_vim_mode_nav},yes}"
  bind h select-pane -L
  bind C-h select-pane -L
  bind j select-pane -D
  bind C-j select-pane -D
  bind k select-pane -U
  bind C-k select-pane -U
  bind l select-pane -R
  bind C-l select-pane -R
%endif

%if "#{==:#{@navin_nav},yes}"
  bind -n M-Left select-pane -L
  bind -n M-Right select-pane -R
  bind -n M-Up select-pane -U
  bind -n M-Down select-pane -D
%endif

%if "#{==:#{@navin_renumber_windows},on}"
  set-option -gq renumber-windows on
%endif

%if "#{==:#{@navin_arrow_nav},yes}"
  set-option -gF repeat-time "#{@navin_repeat_time}"
  bind-key -r M-Left previous-window
  bind-key -r M-Right next-window
  bind-key -r M-Home select-window -t :^
  bind-key -r M-End select-window -t :$
  bind-key -r M-Up switch-client -p
  bind-key -r M-Down switch-client -n
%endif

%if "#{==:#{@navin_layout_nav},yes}"
  bind-key -n M-| select-layout even-horizontal
  bind-key -n M-_ select-layout main-horizontal
  bind-key -n M-\\ select-layout main-vertical
  bind-key -n M-- select-layout even-vertical
  bind-key -n M-= select-layout tiled
  bind-key -n C-M-_ select-layout main-horizontal-mirrored
  bind-key -n C-M-\\ select-layout main-vertical-mirrored
%endif

%if "#{==:#{@navin_tab_nav},yes}"
  bind-key -n C-Tab next-window
  # [TODO] fix this!. The terminal treat it the same as S-Tab, why?
  # bind-key -n C-S-Tab previous-window
%endif
